export const CONFIG = {
  name: "Shahriar Haque Abir",
  nameHL: "Shahriar",
  tagline: "Technical Operations Engineer | Integration Engineer | Application Support Engineer",
  taglineContext: "Enterprise Software · SaaS Platforms · Tier-3 Troubleshooting · API Integrations",
  taglines: [
    "Tier-3 Troubleshooting & RCA",
    "Enterprise SaaS Operations",
    "API & Systems Integration",
    "Incident & SLA Management",
    "SQL & Log Stream Analysis",
    "Technical Solution Consulting",
    "GTM & SDR Operating Models",
  ],
  heroStats: [
    { label: "Years experience in enterprise software & mission-critical support", value: "10+" },
    { label: "Tier-3 incidents resolved weekly across global enterprise clients", value: "40" },
    { label: "Premier international enterprise accounts managed", value: "10" },
  ],
  location: "Berlin, Germany",
  workAuth: "Niederlassungserlaubnis (Permanent resident)",
  profile: `Technical Operations Engineer with 10+ years of experience supporting enterprise software, SaaS platforms, systems integration, and mission-critical production environments. Expertise in Tier-3 troubleshooting, incident management, root cause analysis (RCA), API integrations, SQL analysis, and operational reliability. Led complex deployments, integrations, and critical production environments across North America, APAC, and DACH regions. Recognized for resolving high-impact technical issues, improving platform performance, and driving operational excellence at scale. Trusted to improve system stability, optimize operational processes, and deliver scalable technical solutions through close collaboration with engineering, product, and infrastructure teams.`,
  profileImage: "/profile.jpg",
  contact: [
    { label: "Email", value: "shahriar_abby@hotmail.com", href: "mailto:shahriar_abby@hotmail.com" },
    { label: "LinkedIn", value: "linkedin.com/in/shahriarhaqueabir", href: "https://www.linkedin.com/in/shahriarhaqueabir" },
    { label: "GitHub", value: "github.com/shahriarhaqueabir", href: "https://github.com/shahriarhaqueabir" },
    { label: "CV", value: "Download CV (PDF)", href: "/shahriar-haque-abir-cv.pdf" },
    { label: "Location", value: "Berlin, Germany", href: null },
  ],
  blog: [
    {
      title: "The Tier-3 Mindset: Signals in the Noise",
      date: "March 2024",
      category: "Technical Operations",
      excerpt: "Why production support isn't just about fixing bugs—it's about understanding the complex relationship between code, data, and customer intent.",
      body: "In high-stakes production environments, an error log is just the surface. True Tier-3 troubleshooting requires a 'systems' view. You aren't just looking at a stack trace; you are looking at an intersection of API payloads, database state, and network latency. The goal is to move from 'why did this fail' to 'how do we ensure the system is architecturally resistant to this failure mode.' By standardizing our RCA frameworks, we don't just close tickets; we build product intelligence.",
    },
    {
      title: "Local AI for Technical Support Workflows",
      date: "February 2024",
      category: "AI Automation",
      excerpt: "Exploring the security and utility of running small, high-capability LLMs like Llama 3.2 locally for sensitive support tasks.",
      body: "Data privacy is the biggest hurdle in adopting AI for enterprise support. My work with local LLMs (using WebLLM and Llama 3.2) explores a zero-trust approach where PII never leaves the local environment. By building local proxies that redact and process data before any external transmission, we can leverage agentic workflows for log analysis and solution drafting while maintaining strict compliance with GDPR and corporate governance.",
    },
    {
      title: "Operationalizing GTM for Technical Products",
      date: "January 2024",
      category: "Strategy",
      excerpt: "Bridging the gap between engineering complexity and market-ready sales cycles through technical discovery.",
      body: "Technical products fail in the sales cycle when discovery is shallow. A Lead Technical Solution Consultant's job is to extract the 'real' requirements—the hidden constraints and integration blockers—before a contract is signed. By building automated GTM signals that feed directly from discovery calls into our CRM, we ensure that engineering is never surprised by a client's technical architecture on Day 1 of onboarding.",
    },
  ],
  experience: [
    {
      company: "tripunkt GmbH",
      role: "Software solutions consultant",
      period: "Nov 2020 – March 2026",
      points: [
        "Resolved approximately 40 Tier-3 incidents weekly across global enterprise customers SaaS deployments, troubleshooting API integrations, application services, and database layers.",
        "Managed regression test cycles and validated software releases against database schemas and integration specifications within Docker testing environments.",
        "Identified pre-release defects via API inspection and log auditing, coordinating directly with engineering to verify hotfixes.",
        "Designed and executed international GTM and SDR pipelines for the Pathfinder software suite, building commercial pipelines from inception across NAM, APAC, and DACH.",
        "Owned the full technical and commercial lifecycle for enterprise accounts across NAM, APAC, and DACH serving as the primary bridge between client engineering teams and internal product development.",
        "Personally managed the complete technical and customer lifecycle for 10 premier international enterprise accounts across 3 global regions.",
      ],
    },
    {
      company: "Technische Hochschule Mittelhessen",
      role: "Masters Thesis Work",
      period: "Oct 2019 – April 2020",
      points: [
        "Investigated the degradation behavior of glass optical fiber bundles exposed to high-intensity UV light, with a focus on characterizing performance loss over time.",
        "Designed and assembled fiber optic hardware setups, including precision splicing, gluing, and alignment of optical components.",
        "Conducted structured hardware testing and performance characterization under controlled conditions.",
        "Analyzed measurement data to identify degradation patterns and draw quantitative conclusions.",
        "Documented findings through formal technical reports and research presentations.",
      ],
    },
    {
      company: "TransMIT GmbH",
      role: "Quality Assurance Quality Control of Optical Fibers",
      period: "April 2017 – Nov 2017",
      points: [
        "Assembled fiber optic cables (FOCs) including core, cladding, and connector integration as part of a production/lab workflow.",
        "Performed tubing and adhesive gluing of optical components to specification.",
        "Polished fiber end-faces to optical-grade finish for signal integrity.",
      ],
    },
    {
      company: "Larsen & Toubro",
      role: "Training Coordinator",
      period: "Aug 2015 – Sept 2016",
      points: [
        "Led the technical onboarding and enablement program for incoming engineers across multiple parallel engineering tracks.",
        "Onboarded and mentored 60+ engineers per quarter across 6 concurrent training groups.",
        "Designed and owned the end-to-end onboarding infrastructure — from curriculum engineering to deployment documentation.",
        "Translated dense engineering specifications into structured, accessible learning paths aligned with project delivery objectives.",
        "Managed scheduling, training effectiveness tracking, and coordination across trainers and facilitators.",
      ],
    },
    {
      company: "Earth Telecommunication PVT. LTD.",
      role: "Network Engineer",
      period: "June 2014 – Sept 2015",
      points: [
        "Installed, configured, and maintained LAN/WAN infrastructure including switches, routers, and access points.",
        "Provided on-call technical support for 500+ corporate and residential clients.",
        "Conducted site surveys and led network deployments for new client installations.",
        "Created and maintained technical documentation for network configurations and operational procedures.",
        "Built a Python tool to scan live hosts and aggregate device relationship data, rendering it as an interactive JS/HTML topology graph for real-time component isolation.",
      ],
    },
    {
      company: "Earth Telecommunication (Pvt.) Limited",
      role: "Network Operations Engineer",
      period: "2013 – July 2014",
      points: [
        "Managed network architecture and incident resolution for over 500 SME and enterprise accounts, maintaining strict high-uptime and SLA compliance.",
        "Standardized structural troubleshooting frameworks across localized hardware, multi-layered routing protocols, and configuration layers, decreasing Mean Time to Resolution (MTTR).",
      ],
    },
  ],
  projects: [
    {
      name: "Network Discovery & Topology Mapping",
      desc: "Python-based tool for live host scanning and interactive relationship visualization.",
      context: "Infrastructure environments lacked centralized documentation, complicating incident resolution and path tracing.",
      implementation: "Built a Python tool to scan live hosts and aggregate device relationship data, rendering the output as an interactive JS/HTML topology graph.",
      outcome: "Enabled real-time component isolation and data-path tracing for over 500 accounts, significantly reducing troubleshooting time.",
      stack: ["Python", "JavaScript", "HTML", "Topology Mapping", "Network Operations"],
    },
    {
      name: "Interactive Database Visualizer",
      desc: "Local tool for visual mapping and tracing of complex database relationships.",
      context: "Understanding complex relational schemas often requires a more intuitive approach than reading DDL files or ERD diagrams.",
      implementation: "Developed a tool that parses SQL DDL or live connections to isolate keys and relationships, mapping them into an interactive node-graph UI using ReactFlow and D3.js.",
      outcome: "Provided a high-performance visual interface to trace foreign key dependencies and explore table linkages, reducing onboarding time for new integration engineers.",
      stack: ["React", "ReactFlow", "D3.js", "SQLite", "SQL Parser"],
    },
    {
      name: "Customer Onboarding & Validation Portal",
      desc: "Interactive portal for client data mapping and schema validation.",
      context: "Integration engineers often face friction when mapping client-proprietary data structures to internal API schemas.",
      implementation: "Built a portal for JSON/CSV uploads with an interactive field-mapping interface and a sandboxed validation runner to check transformations against schema constraints.",
      outcome: "Streamlined the onboarding process for technical integrations by providing immediate feedback on data compatibility.",
      stack: ["Next.js", "TypeScript", "Python", "Node.js", "Schema Validation"],
    },
    {
      name: "Log Analysis & Automated Ticketing",
      desc: "Automated error detection and Jira ticket creation workflow.",
      context: "Production support teams need to catch recurring errors early without manual log tailing or ticket spam.",
      implementation: "Developed a log parsing workflow that monitors error thresholds using regex and automatically triggers Jira REST API calls for validated incidents.",
      outcome: "Reduced response times for recurring production errors and improved incident tracking reliability.",
      stack: ["Python", "Regex", "Jira API", "Operational Support"],
    },
    {
      name: "CI-Friendly API Test Automation",
      desc: "Automated API validation workflow for CI/CD pipelines.",
      context: "Ensuring authentication, schema integrity, and edge cases are validated across every deployment cycle.",
      implementation: "Developed a workflow using Postman collections and Newman CLI, integrated into GitHub Actions for automated validation of production-ready APIs.",
      outcome: "Improved release reliability by catching integration regressions and schema mismatches early in the pipeline.",
      stack: ["Postman", "Newman", "GitHub Actions", "CI/CD", "API Testing"],
    },
    {
      name: "Internal AI Gateway Proxy",
      desc: "Security-focused AI proxy for PII redaction and corporate governance.",
      context: "Corporate environments need to leverage LLMs while ensuring strict security, privacy, and data governance.",
      implementation: "Built an async middleware proxy to intercept prompt requests, using regex and NER to redact sensitive data (PII, financial, secrets) before vendor transmission.",
      outcome: "Enabled secure internal LLM usage by providing a transparent governance layer that masks sensitive information.",
      stack: ["Python", "FastAPI", "Regex", "NER", "Security Proxy", "Async Middleware"],
    },
  ],
  skills: [
    {
      group: "Technical Operations",
      items: ["Tier-3 Support", "Incident Management", "Root Cause Analysis (RCA)", "Production Support", "SLA Management", "Troubleshooting Frameworks"],
    },
    {
      group: "Systems Integration",
      items: ["REST APIs", "Application Integration", "Software Deployment", "Configuration Management", "Schema Validation", "Docker Environments"],
    },
    {
      group: "Data & Troubleshooting",
      items: ["SQL (PostgreSQL, MySQL, SQL Server)", "Log Analysis (Grep/Awk)", "API Tracing (Postman/Swagger)", "Data Investigation", "Performance Optimization"],
    },
    {
      group: "Solutions Engineering",
      items: ["Technical Discovery", "Solution Scoping", "PoC Delivery", "RFI/RFP Responses", "Technical Consulting", "Integration Schematics"],
    },
    {
      group: "Infrastructure & Networking",
      items: ["LAN/WAN", "Routing & Switching", "Network Troubleshooting", "IT Security", "Cloud Services", "Linux Admin"],
    },
  ],
  languages: ["English (Native or Bilingual)", "Bangla (Native or Bilingual)", "German (Professional Working)", "Hindi (Limited Working)"],
  certifications: [
    "Networking Foundations: Networking Basics",
    "cisco scaling networks",
    "Goethe-Zertifikat B1",
    "Linux System Engineer: Networking and SSH",
    "cisco interconnecting networks",
  ],
  education: [
    { degree: "Master of Science - MSc, Information and Communication Engineering", school: "Technische Hochschule Mittelhessen, Germany", period: "2016 – 2020" },
    { degree: "Bachelor of Science - BSc, Electrical and Electronics Engineering", school: "North South University, Bangladesh", period: "2009 – 2014" },
  ],
};
