export const CONFIG = {
  name: "Shahriar Haque Abir",
  nameHL: "Shahriar",
  tagline: "Technical Operations · Integration · Application Support Engineer",
  taglineContext: "Enterprise Software · SaaS Platforms · Tier-3 Troubleshooting · API Integrations",
  taglines: [
    "Tier-3 Troubleshooting & RCA",
    "Enterprise SaaS Operations",
    "API & Systems Integration",
    "Incident & SLA Management",
    "SQL & Log Stream Analysis",
    "Technical Solution Consulting",
    "GTM & SDR Operating Models",
  ],
  heroStats: [
    { label: "Years experience in enterprise software & mission-critical support", value: "10+" },
    { label: "Tier-3 incidents resolved weekly across global enterprise clients", value: "40" },
    { label: "Reduction in recurring production incidents through frameworks", value: "30%" },
  ],
  location: "Berlin, Germany",
  workAuth: "Niederlassungserlaubnis (Permanent resident)",
  profile: `Technical Operations Engineer with 10+ years of experience supporting enterprise software, SaaS platforms, systems integration, and mission-critical production environments. Expertise in Tier-3 troubleshooting, incident management, root cause analysis (RCA), API integrations, SQL analysis, and operational reliability. Led complex deployments, integrations, and critical production environments across North America, APAC, and DACH regions. Trusted to improve system stability, optimize operational processes, and deliver scalable technical solutions through close collaboration with engineering, product, and infrastructure teams.`,
  profileImage: "/profile.jpg",
  contact: [
    { label: "Email", value: "shahriar_abby@hotmail.com", href: "mailto:shahriar_abby@hotmail.com" },
    { label: "LinkedIn", value: "linkedin.com/in/shahriarhaqueabir", href: "https://www.linkedin.com/in/shahriarhaqueabir" },
    { label: "GitHub", value: "github.com/shahriarhaqueabir", href: "https://github.com/shahriarhaqueabir" },
    { label: "CV", value: "Download CV (PDF)", href: "/shahriar-haque-abir-cv.pdf" },
    { label: "Location", value: "Berlin, Germany", href: null },
  ],
  blog: [
    {
      title: "The Tier-3 Mindset: Signals in the Noise",
      date: "March 2024",
      category: "Technical Operations",
      excerpt: "Why production support isn't just about fixing bugs—it's about understanding the complex relationship between code, data, and customer intent.",
      body: "In high-stakes production environments, an error log is just the surface. True Tier-3 troubleshooting requires a 'systems' view. You aren't just looking at a stack trace; you are looking at an intersection of API payloads, database state, and network latency. The goal is to move from 'why did this fail' to 'how do we ensure the system is architecturally resistant to this failure mode.' By standardizing our RCA frameworks, we don't just close tickets; we build product intelligence.",
    },
    {
      title: "Local AI for Technical Support Workflows",
      date: "February 2024",
      category: "AI Automation",
      excerpt: "Exploring the security and utility of running small, high-capability LLMs like Llama 3.2 locally for sensitive support tasks.",
      body: "Data privacy is the biggest hurdle in adopting AI for enterprise support. My work with local LLMs (using WebLLM and Llama 3.2) explores a zero-trust approach where PII never leaves the local environment. By building local proxies that redact and process data before any external transmission, we can leverage agentic workflows for log analysis and solution drafting while maintaining strict compliance with GDPR and corporate governance.",
    },
    {
      title: "Operationalizing GTM for Technical Products",
      date: "January 2024",
      category: "Strategy",
      excerpt: "Bridging the gap between engineering complexity and market-ready sales cycles through technical discovery.",
      body: "Technical products fail in the sales cycle when discovery is shallow. A Lead Technical Solution Consultant's job is to extract the 'real' requirements—the hidden constraints and integration blockers—before a contract is signed. By building automated GTM signals that feed directly from discovery calls into our CRM, we ensure that engineering is never surprised by a client's technical architecture on Day 1 of onboarding.",
    },
  ],
  experience: [
    {
      company: "tripunkt GmbH",
      role: "QA and Release Validation",
      period: "2024 – 2026",
      points: [
        "Managed regression test cycles and validated software releases against database schemas and integration specifications within Docker testing environments.",
        "Identified pre-release defects via API payload inspection and log stream auditing, coordinating directly with engineering to verify hotfixes.",
      ],
    },
    {
      company: "tripunkt GmbH",
      role: "Software Solution Consultant",
      period: "2020 – 2024",
      points: [
        "Resolved approximately 40 Tier-3 incidents weekly across global enterprise customers SaaS deployments, troubleshooting API integrations, application services, and database layers.",
        "Isolated production defects using CLI log analysis (grep/awk), API tracing (Postman/Swagger), and cross-database validation (PostgreSQL, MySQL, SQL Server).",
        "Configured, debugged, and documented REST API integration workflows and schemas across Docker-based and on-prem environments.",
        "Standardised global troubleshooting frameworks and escalation procedures, driving a 30% reduction in recurring production incidents.",
        "Authored technical integration diagrams and operational runbooks to support enterprise onboarding across NAM, APAC, and DACH regions.",
      ],
    },
    {
      company: "Larsen and Toubro",
      role: "Technical Training Coordinator",
      period: "2015 – 2016",
      points: [
        "Led the technical enablement, onboarding infrastructure design, curriculum engineering, and mentorship of over 60 incoming engineers across parallel engineering tracks per quarter.",
        "Formalized repeatable technical knowledge-transfer, deployment documentation, and dense engineering specifications into structured, accessible learning paths.",
        "Aligned technical delivery teams with corporate project objectives and maximized baseline KPI visibility.",
      ],
    },
    {
      company: "Earth Telecommunication Pvt. Ltd.",
      role: "Network Operations Engineer",
      period: "2013 – 2015",
      points: [
        "Managed network architecture and incident resolution for over 500 SME and enterprise accounts, coordinated field services, and installation scheduling.",
        "Maintained strict high-uptime and SLA compliance through structured troubleshooting frameworks across multi-layered routing protocols.",
        "Decreased Mean Time to Resolution (MTTR) by standardizing hardware and configuration layer diagnostics.",
        "Built a Python tool to scan live hosts and aggregate device relationship data, rendering it as an interactive topology graph for real-time component isolation.",
      ],
    },
  ],
  projects: [
    {
      name: "Interactive Database Visualizer",
      desc: "Local tool for visual mapping and tracing of complex database relationships.",
      context: "Understanding complex relational schemas often requires a more intuitive approach than reading DDL files or ERD diagrams.",
      implementation: "Developed a tool that parses SQL DDL or live connections to isolate keys and relationships, mapping them into an interactive node-graph UI using ReactFlow and D3.js.",
      outcome: "Provided a high-performance visual interface to trace foreign key dependencies and explore table linkages, reducing onboarding time for new integration engineers.",
      stack: ["React", "ReactFlow", "D3.js", "SQLite", "SQL Parser"],
    },
    {
      name: "Customer Onboarding & Validation Portal",
      desc: "Interactive portal for client data mapping and schema validation.",
      context: "Integration engineers often face friction when mapping client-proprietary data structures to internal API schemas.",
      implementation: "Built a portal for JSON/CSV uploads with an interactive field-mapping interface and a sandboxed validation runner to check transformations against schema constraints.",
      outcome: "Streamlined the onboarding process for technical integrations by providing immediate feedback on data compatibility.",
      stack: ["Next.js", "TypeScript", "Python", "Node.js", "Schema Validation"],
    },
    {
      name: "Log Analysis & Automated Ticketing",
      desc: "Automated error detection and Jira ticket creation workflow.",
      context: "Production support teams need to catch recurring errors early without manual log tailing or ticket spam.",
      implementation: "Developed a log parsing workflow that monitors error thresholds using regex and automatically triggers Jira REST API calls for validated incidents.",
      outcome: "Reduced response times for recurring production errors and improved incident tracking reliability by 30%.",
      stack: ["Python", "Regex", "Jira API", "Operational Support"],
    },
    {
      name: "Network Discovery & Topology Mapping",
      desc: "Python utility for live host discovery and relationship visualization.",
      context: "Infrastructure environments at Earth Telecommunication lacked centralized documentation, complicating incident resolution.",
      implementation: "Developed a Python application integrating nmap for subnet scanning. Processed results into JSON to generate interactive topology graphs.",
      outcome: "Improved network visibility and reduced MTTR by standardizing infrastructure documentation and relationship tracing.",
      stack: ["Python", "nmap", "NetworkX", "D3.js", "JSON"],
    },
    {
      name: "CI-Friendly API Test Automation",
      desc: "Automated API validation workflow for CI/CD pipelines.",
      context: "Ensuring authentication, schema integrity, and edge cases are validated across every deployment cycle.",
      implementation: "Developed a workflow using Postman collections and Newman CLI, integrated into GitHub Actions for automated validation of production-ready APIs.",
      outcome: "Improved release reliability by catching integration regressions and schema mismatches early in the pipeline.",
      stack: ["Postman", "Newman", "GitHub Actions", "CI/CD", "API Testing"],
    },
    {
      name: "Internal AI Gateway Proxy",
      desc: "Security-focused AI proxy for PII redaction and corporate governance.",
      context: "Corporate environments need to leverage LLMs while ensuring strict security, privacy, and data governance.",
      implementation: "Built an async middleware proxy to intercept prompt requests, using regex and NER to redact sensitive data (PII, financial, secrets) before vendor transmission.",
      outcome: "Enabled secure internal LLM usage by providing a transparent governance layer that masks sensitive information.",
      stack: ["Python", "FastAPI", "Regex", "NER", "Security Proxy", "Async Middleware"],
    },
  ],
  skills: [
    {
      group: "Technical Operations",
      items: ["Tier-3 Support", "Incident Management", "Root Cause Analysis (RCA)", "Production Support", "SLA Management", "Troubleshooting Frameworks"],
    },
    {
      group: "Systems Integration",
      items: ["REST APIs", "Application Integration", "Software Deployment", "Configuration Management", "Schema Validation", "Docker Environments"],
    },
    {
      group: "Data & Troubleshooting",
      items: ["SQL (PostgreSQL, MySQL, SQL Server)", "Log Analysis (Grep/Awk)", "API Tracing (Postman/Swagger)", "Data Investigation", "Performance Optimization"],
    },
    {
      group: "Solutions Engineering",
      items: ["Technical Discovery", "Solution Scoping", "PoC Delivery", "RFI/RFP Responses", "Technical Consulting", "Integration Schematics"],
    },
    {
      group: "Infrastructure & Networking",
      items: ["LAN/WAN", "Routing & Switching", "Network Troubleshooting", "IT Security", "Cloud Services", "Linux Admin"],
    },
  ],
  languages: ["English (C2)", "Bengali (C2)", "German (B2)", "Hindi (B1)"],
  certifications: ["Cisco Scaling Networks", "Networking Foundations", "Linux System Engineer", "Cyber Security Foundation", "Goethe-Zertifikat B1"],
  education: [
    { degree: "M.Sc. Information and Communication Engineering", school: "Technische Hochschule Mittelhessen, Germany", period: "2016 – 2020" },
    { degree: "B.Sc. Electrical and Electronic Engineering", school: "North South University, Bangladesh", period: "2009 – 2013" },
  ],
};
